---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio

spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2023-12-23T07-19-11Z@sha256:47d5b01cc3020efa39aac112a7cbc919af5fb18f9ebc63bda31683590715c42b
      - name: minio-init
        image: "minio/mc:RELEASE.2023-12-29T20-15-29Z@sha256:aec83b55bc7949223395c5a7fad3673362cb45c28eea0596f560abe947e3547b"